### ISSUE TITLE
Experiment design about this study

### ISSUE THREAD

**Issue by Kaoping** [cmsantosm/RiceMbiomeResponse#1]
Hi Christian,

Recently I read you paper "Acquisition of a complex root microbiome reshapes the transcriptomes of rice plants", it's really an excellent story. I am curious about two things:(1) why you set up the potted-soil plant controls ? If this potted-soil plant treatments mean you added soil rather than soil suspension after 7 germination? Because I think adding soil and adding soil suspension are the same treatment in this study. I am not sure I understand that correctly. (2) I recognized you picked out the core OTUs, but I can't find out how you defined the OTU is core OTU. 

Thanks for your time.
Best,
Kaoping

**Comment by cmsantosm** [comment]
Hi Kaoping,

Thanks for your questions:

1) The soil-grown potted plants are very different from the soil-inoculated plants grown in semi-hydroponic containers. For the soil-grown controls, we transplanted 7-day-old axenic seedlings to potted agricultural soils and profiled their microbiomes 14 days post-transplantation. For soil-inoculated plants, we grew rice seedlings in closed sterile containers holding calcined clay and plant-growth media. The 7-day-old seedlings were inoculated with a diluted soil slurry derived from the same soils used for the soil-grown controls.  

2) You can find the core OTU analysis in the mbiome_soil_diff.Rmd notebook (lines 126-193)

**Comment by Kaoping** [comment]
Thank you for the helpful explanation. This makes a lot more sense to me now.
